language: php

matrix:
  include:
  - php: 7.1

  fast_finish: true

install:
  - scripts/ci-install.sh

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

script:
  - composer test:clover
  - composer lint

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 7.1"

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    slack: crazyfactory:Z3NJKlj5jdPOE1YrjPPyDPKb
