<?php
/**
 * BoxContentsFeeDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CrazyFactory\Spapi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CrazyFactory\Spapi\Client;

/**
 * BoxContentsFeeDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description The manual processing fee per unit and total fee for a shipment.
 * @package     CrazyFactory\Spapi\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BoxContentsFeeDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BoxContentsFeeDetails"
     */
    public function testBoxContentsFeeDetails()
    {
    }

    /**
     * Test attribute "total_units"
     */
    public function testPropertyTotalUnits()
    {
    }

    /**
     * Test attribute "fee_per_unit"
     */
    public function testPropertyFeePerUnit()
    {
    }

    /**
     * Test attribute "total_fee"
     */
    public function testPropertyTotalFee()
    {
    }
}
