<?php
/**
 * FbaInboundApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CrazyFactory\Spapi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CrazyFactory\Spapi\Client;

use \CrazyFactory\Spapi\Client\Configuration;
use \CrazyFactory\Spapi\Client\ApiException;
use \CrazyFactory\Spapi\Client\ObjectSerializer;

/**
 * FbaInboundApiTest Class Doc Comment
 *
 * @category Class
 * @package  CrazyFactory\Spapi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FbaInboundApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for confirmPreorder
     *
     * .
     *
     */
    public function testConfirmPreorder()
    {
    }

    /**
     * Test case for confirmTransport
     *
     * .
     *
     */
    public function testConfirmTransport()
    {
    }

    /**
     * Test case for createInboundShipment
     *
     * .
     *
     */
    public function testCreateInboundShipment()
    {
    }

    /**
     * Test case for createInboundShipmentPlan
     *
     * .
     *
     */
    public function testCreateInboundShipmentPlan()
    {
    }

    /**
     * Test case for estimateTransport
     *
     * .
     *
     */
    public function testEstimateTransport()
    {
    }

    /**
     * Test case for getBillOfLading
     *
     * .
     *
     */
    public function testGetBillOfLading()
    {
    }

    /**
     * Test case for getInboundGuidance
     *
     * .
     *
     */
    public function testGetInboundGuidance()
    {
    }

    /**
     * Test case for getLabels
     *
     * .
     *
     */
    public function testGetLabels()
    {
    }

    /**
     * Test case for getPreorderInfo
     *
     * .
     *
     */
    public function testGetPreorderInfo()
    {
    }

    /**
     * Test case for getPrepInstructions
     *
     * .
     *
     */
    public function testGetPrepInstructions()
    {
    }

    /**
     * Test case for getShipmentItems
     *
     * .
     *
     */
    public function testGetShipmentItems()
    {
    }

    /**
     * Test case for getShipmentItemsByShipmentId
     *
     * .
     *
     */
    public function testGetShipmentItemsByShipmentId()
    {
    }

    /**
     * Test case for getShipments
     *
     * .
     *
     */
    public function testGetShipments()
    {
    }

    /**
     * Test case for getTransportDetails
     *
     * .
     *
     */
    public function testGetTransportDetails()
    {
    }

    /**
     * Test case for putTransportDetails
     *
     * .
     *
     */
    public function testPutTransportDetails()
    {
    }

    /**
     * Test case for updateInboundShipment
     *
     * .
     *
     */
    public function testUpdateInboundShipment()
    {
    }

    /**
     * Test case for voidTransport
     *
     * .
     *
     */
    public function testVoidTransport()
    {
    }
}
